version: "3"

services:
  front-end:
      container_name: todo-front-container
      #image: todo-front:latest
      build:
          context: ./my-app
          dockerfile: Dockerfile
      command: yarn start
      ports:
        - "3000:3000"
      #volumes:
     # - ./: ./app
     # - /app/node_modules
      networks:
          - todo-networks
  back-end:
      container_name: todo-backend-container
     # image: todo-backend:latest
      build:
        context: ./todo-backend
        dockerfile: Dockerfile
      ports:
      - "8090:8090"
      networks:
          - todo-networks
networks:
  todo-networks:
    driver: bridge
